- name: create dumpall file
  template:
    src: dumpdir.sh.j2
    dest: "{{ dump_file_name }}"
    mode: a+x

- name: cron task
  cron:
    name: "{{ dump_cron_task_name }}"
    hour: "{{ dump_hour }}"
    minute: "{{ dump_minute }}"
    job: "{{ dump_file_name }}"